#-------------------------------
# General Site Settings

title: BUET FPL
logo: logo.png
email: fplbuet@gmail.com
page: https://www.facebook.com/buet.fpl
group:

menu:
- {name: About, link: '/about/'}
- {name: Blog, link: '/blog/'}
- {name: Winners, link: '/winners/'}

#------------------------------- Analytics
google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Header Section

banner:
  banner-title: Welcome to the <br> home of BUET FPL

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/buet.fpl"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  We are here to make Fantasy Premier League fun and gainful. All BUET students & alumnis are welcomed 
  to join our Facebook group to compete in different BUET FPL leagues and fight for the glory!
  Discuss football & FPL with us. It’s FREE to play and you can win great prizes!
blurb-btn-link: '/about'
blurb-btn-name: Learn more

winner:
  - title : "Anayet Hossain"
    image : "assets/images/blog/sep-w.jpg"
    designation : "September"
    
  - title : "Azmain Iqtidar Nipun"
    image : "assets/images/blog/oct-m.png"
    designation : "October"
  

#-------------------------------
# Tournaments Section

tournament-title: Tournaments
tournament:
- {name: Classic Top 10, date: '1', organization: 'Defeat hundreds to claim the glory the classic way'}
- {name: Head-to-Head, date: '2', organization: 'Bring the opponents down...one by one'}
- {name: The Walking Dead, date: '3', organization: 'Run, do not walk. Avoid falling behind'}
- {name: Six Hall Champions, date: '4', organization: 'Claim the crown as the FPL king of your hall'}
- {name: Cup MVP, date: '5', organization: 'The best of the best of all the halls'}


#-------------------------------
# Sponsors Section

sponsor-items:
  - name: "Saif Sporting Club"
    image: "assets/images/testimonial/ssc.png"
    designation : "Sponsored by"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Bangladesh Football Federation"
    image: "assets/images/testimonial/bff.png"
    designation : "Powered by"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."